Userdata
bmacharia/terraform-aws pull request #11
Opened 2022-09-26 18:03 UTC by bmacharia

2022-09-26 21:54 UTC, vladimirmukhin requested changes

2022-09-26 21:54 UTC, vladimirmukhin commented on instance.tf
> +  }
```suggestion
    cidr_blocks = ["${var.my_public_ip}/32"]
  }
```

2022-09-27 16:59 UTC, bmacharia commented on instance.tf
> +  }
extra line has been deleted

2022-09-27 17:03 UTC, vladimirmukhin approved these changes

2022-09-27 18:05 UTC, merged